# ==============================================
# controller.py
# Attitude control algorithms for ADCS
# ----------------------------------------------
# This module implements attitude control algorithms for the satellite,
# primarily the B-dot controller for detumbling using magnetorquers.
#
# - Implements B-dot control logic (cross-product form)
# - Placeholder for additional controllers (e.g., PD, quaternion feedback)
# - Outputs control torques for actuators (e.g., magnetorquers)
# ==============================================


import numpy as np

from config import K_BDOT

# === B-dot Controller (Cross-Product Form) ===
def b_dot_controller(B_filtered, omega_filtered):
    """
    Calculates the commanded magnetic moment for B-dot control using the cross-product form.
    This controller aims to reduce the satellite's angular velocity by generating a magnetic moment
    perpendicular to both the angular velocity and the measured magnetic field.

    Args:
        B_filtered (np.ndarray): Current filtered magnetic field vector in body frame (Tesla)
        omega_filtered (np.ndarray): Current filtered angular velocity vector in body frame (rad/s)

    Returns:
        m_out (np.ndarray): Commanded magnetic moment vector for magnetorquers (A·m²)
    """
    
    m_out = K_BDOT * np.cross(omega_filtered, B_filtered)
    
    return m_out

def get_control_torque(m_out, B_body_true):
    """
    Computes the control torque generated by the magnetorquers in the presence of the local magnetic field.
    The torque is given by the cross product of the commanded magnetic moment and the true magnetic field vector.

    Args:
        m_out (np.ndarray): Commanded magnetic moment vector (A·m²)
        B_body_true (np.ndarray): True magnetic field vector in body frame (Tesla)

    Returns:
        current_torque (np.ndarray): Resulting control torque vector (N·m)
    """
    
    current_torque = np.cross(m_out, B_body_true)
    return current_torque
