# ==============================================
# sensors.py
# Simulated onboard sensor data
# ----------------------------------------------
# This module simulates readings from gyroscopes and magnetometers onboard a satellite.
# It adds realistic noise, bias, and drift to the sensor outputs, and models the effect
# of magnetorquer actuation on the magnetometer. These simulated sensors are used for
# testing attitude estimation and control algorithms in the ADCS simulation.
#
# - Simulates readings from gyroscopes and magnetometers
# - Adds realistic noise, bias, and drift
# - Used for testing attitude estimation and control
# - Can be extended for more complex sensor models or additional sensors
# ==============================================


import numpy as np
from config import MAG_DISTURBANCE_GAIN


# =============================
# Sensor noise, bias, and drift parameters (typical for CubeSat-class sensors)
# =============================
# Gyroscope noise standard deviation [rad/s] (white noise)
GYRO_NOISE_STD = 0.001   # [rad/s] white noise std dev


# Magnetometer noise standard deviation [Tesla] (white noise, 50 nT)
MAG_NOISE_STD = 50e-7     # [Tesla] white noise std dev (50 nT)

def read_gyroscope(omega_true, dt, state):
    """
    Simulate gyroscope reading with noise, bias, and drift.
    The gyroscope measures the satellite's angular velocity, but real sensors are affected by
    white noise, bias, and slow random drift (random walk). This function can be extended to
    include more realistic bias and drift models.

    Args:
        omega_true (np.ndarray): True angular velocity [wx, wy, wz] (rad/s)
        dt (float): Timestep (s)
        state (dict): Holds persistent bias for the gyroscope
    Returns:
        omega_meas (np.ndarray): Measured angular velocity (rad/s)
        state (dict): Updated state dict
    """
    state['gyro_bias'] = 0
    # Uncomment below for random walk bias model:
    # if 'gyro_bias' not in state:
    #     # Initialize bias as a random vector
    #     state['gyro_bias'] = np.random.normal(0, 1, 3)
    # # Bias random walk (drift)
    # state['gyro_bias'] += np.random.normal(0, 1 * np.sqrt(dt), 3)
    # White noise
    noise = np.random.normal(0, GYRO_NOISE_STD, 3)
    omega_meas = omega_true + state['gyro_bias'] + noise
    return omega_meas, state


def read_magnetometer(magnetic_field_body, m_out, dt, state):
    """
    Simulate magnetometer reading with noise, bias, drift, and magnetorquer disturbance.
    The magnetometer measures the local magnetic field, but is affected by white noise,
    bias, drift, and the magnetic field generated by the satellite's own magnetorquers.

    Args:
        magnetic_field_body (np.ndarray): True magnetic field in body frame [Bx, By, Bz] (Tesla)
        m_out (np.ndarray): Commanded magnetic moment from controller [mx, my, mz] (A·m²)
        dt (float): Timestep (s)
        state (dict): Holds persistent bias for the magnetometer
    Returns:
        B_meas (np.ndarray): Measured magnetic field (Tesla)
        state (dict): Updated state dict
    """
    # Add disturbance from magnetorquers (linear model)
    B_disturbance = MAG_DISTURBANCE_GAIN * m_out
    B_total_true = magnetic_field_body + B_disturbance      
    
    # White noise
    noise = np.random.normal(0, MAG_NOISE_STD, 3)
    B_meas = B_total_true + noise
    return B_meas, state

